fail_fast: true

repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        name: black
        language_version: python3.11.9
        types_or:
          - python
          - pyi
          - jupyter

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
        name: ruff
        language_version: python3.11.9
        types_or:
          - python
          - pyi
        args: [ --fix ]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        name: mypy
        language_version: python3.11.9
        types_or:
          - python
          - pyi
        args: [ --ignore-missing-imports ]
      
  - repo: local
    hooks:
      - id: pyright
        name: pyright
        entry: pyright
        language: system
        types_or:
          - python
          - pyi
        pass_filenames: false

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest tests/
        language: system
        types_or:
          - python
          - pyi
        pass_filenames: false
        always_run: true