fail_fast: true

repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types_or:
          - python
          - pyi
          - jupyter

  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: ruff
        language: system
        types_or:
          - python
          - pyi
        args: [--fix]

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types_or:
          - python
          - pyi

  # - repo: local
  #   hooks:
  #     - id: pytest
  #       name: pytest
  #       entry: pytest tests/
  #       language: system
  #       types_or:
  #         - python
  #         - pyi
  #       pass_filenames: false
  #       always_run: true